/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        birth: {
          red: '#e8000d',
          black: '#0a0a0a',
          white: '#ffffff',
          gray: '#f5f5f5',
          'gray-2': '#e8e8e8',
          'gray-3': '#aaaaaa',
          'gray-4': '#666666',
        },
        // Paleta "Aetheric Minimal" (DESIGN.md / mockup Stitch) — tokens
        // Material 3 usados tal cual por el mockup de referencia.
        tertiary: '#00647f',
        'inverse-primary': '#ffb4aa',
        'primary-fixed-dim': '#ffb4aa',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'on-secondary-container': '#fefcff',
        'inverse-on-surface': '#f1f0f5',
        'outline-variant': '#e7bdb7',
        'surface-container-high': '#e9e7ed',
        'primary-fixed': '#ffdad5',
        'error-container': '#ffdad6',
        'on-surface': '#1a1b1f',
        'on-primary': '#ffffff',
        surface: '#faf9fe',
        'surface-bright': '#faf9fe',
        'on-tertiary-fixed-variant': '#004d63',
        'tertiary-fixed-dim': '#68d3fc',
        'surface-container': '#eeedf3',
        'on-surface-variant': '#5d3f3b',
        'on-tertiary-fixed': '#001f29',
        outline: '#926f6a',
        'on-error-container': '#93000a',
        'on-primary-container': '#fffbff',
        'on-secondary-fixed': '#001a41',
        'surface-variant': '#e3e2e7',
        'on-tertiary-container': '#fafdff',
        'tertiary-container': '#007fa0',
        'primary-container': '#e2241f',
        'surface-container-highest': '#e3e2e7',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#004493',
        'surface-tint': '#c0000a',
        'on-primary-fixed-variant': '#930005',
        'on-error': '#ffffff',
        'surface-dim': '#dad9df',
        'surface-container-lowest': '#ffffff',
        primary: '#bc000a',
        'secondary-fixed-dim': '#adc6ff',
        secondary: '#0058bc',
        'on-primary-fixed': '#410001',
        'on-background': '#1a1b1f',
        'inverse-surface': '#2f3034',
        background: '#F5F5F7',
        'secondary-fixed': '#d8e2ff',
        'tertiary-fixed': '#bbe9ff',
        'secondary-container': '#0070eb',
      },
      fontFamily: {
        barlow: ['"Barlow Condensed"', 'sans-serif'],
        dm: ['"DM Sans"', 'sans-serif'],
      },
      borderRadius: {
        widget: '32px',
      },
      boxShadow: {
        glass: '0 8px 32px rgba(10,10,10,0.08)',
        'glass-sm': '0 4px 16px rgba(10,10,10,0.06)',
        'glass-dark': '0 8px 32px rgba(0,0,0,0.35)',
        glow: '0 0 24px rgba(232,0,13,0.35)',
      },
    },
  },
  plugins: [],
}
